[package]
name = "damim"
version = "0.1.0"
authors = ["Marko Golob"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
